### ISSUE TITLE
Is there a release with user/questions?

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#126]
I tried to install latest 1.2 release to anatomy:
     pip install proso-apps==1.2.17

But user/questions is not there.

I'm a bit confused, but I think that there is not a 1.X release with user/questions. I think I should release this commit: https://github.com/adaptive-learning/proso-apps/commit/3c5d69c922590f1cacc6b2a881238a0e727bca91 , but I'm not sure if it's the right one.

**Comment by papousek** [comment]
The only version containing this feature is 2.0.0.
