### ISSUE TITLE
Change logging "There is a wrong value -1 for response time" from ERROR to WARNING

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#143]
So that it does not appear in error emails.

**Comment by papousek** [comment]
I understand that this issue is related to only a small amount of data, but ... Is this really what we want? Do we have at least a hypothesis why it is happening?

**Comment by slaweet** [comment]
What is your concern?
If I didn't work on this issue so far (due to it's low priority), I don't see how getting more emails about it wil help it.

I have no idea why is it happening, but getting more emails about it won't help me figure it out. I've been getting those emails for a long time and I realized that I'm no longer looking at ANY ERROR emails, because half of them is this error. So the whole error reporting becames useless.

**Comment by papousek** [comment]
OK, we have +/- 10 answers with wrong response time per day, so I will turn it off.
