### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by MatheusArrudaLab** [adaptive-learning/proso-apps#149]
Dear developers , I am trying to install proso -apps locally to verify the behavior of an adaptive system, but when trying to install is returned me this error:

```
(proso-apps) matheus@matheus-VirtualBox:~/proso-apps$ make install
pip install flake8
Collecting flake8
  Using cached flake8-2.5.4-py2.py3-none-any.whl
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8)
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8)
  Using cached pyflakes-1.0.0-py2.py3-none-any.whl
Collecting mccabe<0.5,>=0.2.1 (from flake8)
  Using cached mccabe-0.4.0-py2.py3-none-any.whl
Installing collected packages: pep8, pyflakes, mccabe, flake8
Successfully installed flake8-2.5.4 mccabe-0.4.0 pep8-1.7.0 pyflakes-1.0.0
flake8 --ignore=E501,E225,E123,E128,W503,E731 --exclude=*/migrations/*.py,*/static/bower_components,setup.py,docs/conf.py,.ropeproject .
./proso/models/environment.py:12:29: E901 SyntaxError: invalid syntax
./proso/models/item_selection.py:16:31: E901 SyntaxError: invalid syntax
./proso/models/option_selection.py:19:33: E901 SyntaxError: invalid syntax
./proso/models/prediction.py:8:33: E901 SyntaxError: invalid syntax
./proso_flashcards/flashcard_construction.py:23:27: E901 SyntaxError: invalid syntax
Makefile:78: recipe for target 'check' failed
make: *** [check] Error 1
```

All items have been installed , but in your own the python2.7 and python3.5
Could you help me about it ?

**Comment by papousek** [comment]
Hi Mateus,

you are probably the first user of proso-apps outside our research group. Firstly, I would like to apologize you for a lot of undocumented stuff and not so stable development. **What exactly is your motivation to use proso-apps?**

The problematic syntax in your case is:

```python
class Example(metaclass=abc.ABCMeta)
```

This syntax is not supported by Python 2.7. If you want to run your own installation of proso-apps, version 3.X is required and we recommend version 3.5.

I would also recommend you to use pip to installed last released version.

**Comment by MatheusArrudaLab** [comment]
Hello Papousek ,
I have studied the adaptive education for some time, and would like to understand the functioning of an adaptive system and I was very excited to learn that there is your group working on it openly .
The biggest problem is that I 've never worked with Linux and has three weeks I'm trying to run the code and can not , with your tips I will see if I can and if possible would like to contribute with you on something .
I made the request in transifex to help in the translation into Portuguese of Brazil

**Comment by papousek** [comment]
Interesting!

If you want to run a demo, load demo data from our geography app (https://outlinemaps.org) and run testproject:
```
./manage.py testproject/test_data/flashcards/geography.json
./manage.py runserver
```

After this import you can visit (for example) API for instructional policy:
```
http://localhost:8000/models/practice?html&filter=[["africa/state"]]&limit=1
```

Be aware we use caching a lot. Caching is disabled for testproject, so testproject is quite slow.
