### ISSUE TITLE
Issues with subscription

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#179]
* [ ] price should be send to gopay times 100
* [ ] after payment the status is still CREATED

**Comment by papousek** [comment]
1. Fixed by 5aeb9286ede0e572cb271c3d0f9b57c1cacd4240.
2. This is tricky part, because payment is updated by a callback from gopay and this callback is set to anatom.cz). You can force to update status of payments by executing `./manage.py refresh_payments`.
