### ISSUE TITLE
/models/to_practice/?stats=true has always practiced=true

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#183]
Observed here:
https://staging.anatom.cz/relations/

Which calls this:
https://staging.anatom.cz/models/to_practice/?debug=true&all=True&filter=%5B%5B%22category%2Frelations%22%5D%5D&language=cs&stats=true&without_contexts=True

Even with a new user in an anonymous window.

**Comment by papousek** [comment]
I will look at it.

**Comment by papousek** [comment]
Fixed in version 3.9.3.
