### ISSUE TITLE
/models/practice/ is slow in anatom.cz

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#187]
The following request is less than 1kB in size, so imo it should take at most 100ms. 
Now it takes around 1s.
https://anatom.cz/models/practice/?filter=%5B%5B%22category%2F01%22%5D,%5B%22category%2Fimages%22%5D%5D&language=cs&limit=2&without_contexts=1

**Comment by papousek** [comment]
The most time consuming part of the response is computation of predictions. I will try to speed it up.

**Comment by slaweet** [comment]
It's quite common that it takes even 5s, see the big yellow bar:
https://tools.pingdom.com/#!/bdpq04/https://anatom.cz/practice/01/

**Comment by papousek** [comment]
@slaweet I know, see https://github.com/adaptive-learning/anatomy/issues/62 for my analysis. I will try to fix it with high priority.
