### ISSUE TITLE
Allow specify number of options with respect to selected direction

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#52]
In geography open question is allowed only in one direction, this is currently not possible with proso_flashcards.

**Comment by thran** [comment]
to remove open questions for flashacards with direction "from description to term" add following  to you config file:

    option_selector:
        class: proso.models.option_selection.ConfusingOptionSelection
            parameters:
                max_options: 6
                allow_zero_options_restriction: True
