### ISSUE TITLE
Practice options should be of the same type as the asked item

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#58]
I just got a question with options:
- Venezuela
- Kuwait
- Lake Onega
- Aral Sea

With this config:
```
         option_selector:
            class: proso.models.option_selection.RandomOptionSelection
```

**Comment by slaweet** [comment]
It also seems to ignore the map I'm practicing.
I just got options:
- Switzerland
- Syr Darya

in Europe

**Comment by thran** [comment]
Can you reproduce the bug with Syr Darya? It seems that is not possible. 
Context of Syr Darya is world, I guess that Switzerland can be on same context. However it is not europe...
