### ISSUE TITLE
Add more stats to Categories

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#68]
For maps overview page we need this data for each category:
- [x] number of flashcards
- [x] number of practiced flashcards
- [x] number of learned flashcards
- [x] number of answers
- [x] number of correct answers

We need the data also separately for each flashcard type (state, city, ..) within the categories, but if it is too difficult, we might consider creating subcategories for each flashcard type.

**Comment by thran** [comment]
How is "number of flashcards" problem solved<

**Comment by slaweet** [comment]
There is list of children, so I can take it's length

**Comment by thran** [comment]
Childern of category are categories or term (in some cases there are none) and can be used in model. I recommend to do not use these enviroment informations. 
We are going implement new resource, which provide stats for selected groups of flashcards (similar as in practice, but for more groups).

**Comment by thran** [comment]
Maybe some optimalization will be needed
