### ISSUE TITLE
Avoid Exception: There are no options for multiple-choice question!

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps#80]
We discussed that this exception can be fixed by disallowing contexts with single term in the imported flashcards. That is not true. 
The error also appears when there are multiple terms on the context, but just one in the given category.  Such term should not be practiced in that situation.

**Comment by papousek** [comment]
I've updated the code to do the following:
 - look at possible options (=> option sets)
 - if the given option set, look at "proso_flashcards.empty_option_set.force_direction" value
 - if the value is set to "d2t" or "t2d", set the direction of the question
 - option selector returns zero options in case of empty option set
