### ISSUE TITLE
logging and reporting of javascript errors 

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/proso-apps#91]
We should use something like https://github.com/moqada/django-js-error-logging as soon as possible.

**Comment by slaweet** [comment]
I tried 
https://github.com/moqada/django-js-error-logging
and
https://github.com/jojax/django-js-error-hook
both are obsolete (~2 since last commit) and not compatible with Django 1.7

**Comment by papousek** [comment]
I am implementing similar functionality to proso-apps.

**Comment by papousek** [comment]
The feature is turned on by setting proso_common.logging.js_errors to true.
